calendar_screen first commit
grauralex92/my-endava pull request #27
Opened 2019-10-14 10:27 UTC by dalia2112

2019-10-14 11:57 UTC, gabrielblaj07 commented on app/src/main/java/com/endava/myendava/fragments/CalendarFragment.java
> +    @BindView(R.id.projects_list_parent)
wrong naming

2019-10-14 11:58 UTC, gabrielblaj07 commented on app/src/main/res/layout/fragment_calendar.xml
> +    <Switch
Make the switch look like in the design

2019-10-14 11:58 UTC, gabrielblaj07 commented on app/src/main/res/layout/fragment_calendar.xml
> +        android:id="@+id/projects_list_parent"
wrong naming

2019-10-14 11:59 UTC, gabrielblaj07 commented on app/src/main/res/layout/item_event.xml
> +    <ProgressBar
the progress bar should have round corners

2019-10-15 10:23 UTC, gabrielblaj07 commented on app/src/main/res/values/colors.xml
> +    <color name="grey3">#828282</color>
😞

2019-10-15 10:24 UTC, gabrielblaj07 commented on app/src/main/java/com/endava/myendava/adapters/CalendarDayAdapter.java
> +    private int getRecyclerWidth() {
Nice one 😮

2019-10-15 10:25 UTC, gabrielblaj07 commented on app/src/main/res/drawable/progress_bar_shape.xml
> +            <corners android:radius="8dp" />
Once upon a time there was a file called dimens.xml

2019-10-15 10:26 UTC, gabrielblaj07 commented on app/src/main/res/drawable/switch_thumb_selector.xml
> +            <stroke android:width="4dp" android:color="#0000ffff" />
Once upon a time there was a file called dimens.xml (and colors.xml as well)

2019-10-15 10:26 UTC, gabrielblaj07 commented on app/src/main/res/drawable/switch_track_selector.xml
> +    <item android:state_checked="false">
dimens and colors

2019-10-15 10:28 UTC, dalia2112 commented on app/src/main/java/com/endava/myendava/adapters/CalendarDayAdapter.java
> +    private int getRecyclerWidth() {
..........................................

2019-10-15 10:29 UTC, dalia2112 commented on app/src/main/res/drawable/progress_bar_shape.xml
> +            <corners android:radius="8dp" />
😭

2019-10-15 10:36 UTC, grauralex92 requested changes

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/adapters/CalendarDayAdapter.java
> +    private List<CalendarDay> mCalendarDayList;
as discussed with Gabi also, I would like to renounce the mStuff naming and continue without the m prefix. there is an extra line between context and list

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/adapters/CalendarDayAdapter.java
> +    private List<CalendarDay> mCalendarDayList;
@soundrob be aware of the naming discussion here

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/adapters/EventAdapter.java
> +public class EventAdapter extends RecyclerView.Adapter<EventAdapter.EventViewHolder> {
Event**s**Adapter? 😛

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/adapters/EventAdapter.java
> +    public static final String TRAINING_EVENT = "Training";
duplicate code ... it exist also in the other adapter. please extract in from the adapters in a common place

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/adapters/EventAdapter.java
> +    private List<Event> mEvents;
same as in the other adapter

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/adapters/EventAdapter.java
> +        private int getEventColor(String event) {
duplicate code

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/adapters/EventParentAdapter.java
> +public class EventParentAdapter extends RecyclerView.Adapter<EventParentAdapter.ProjectParentViewHolder> {
no need for this adapter ... please see https://medium.com/@saber.solooki/sticky-header-for-recyclerview-c0eb551c3f68

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/fragments/CalendarFragment.java
> +
don't use the mNaming anymore ... also there is an extra blank space 😛

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/fragments/CalendarFragment.java
> +    private List<CalendarDay> getCalendarDayList() {
move data generation to another file which can be easily deleted after real implementation

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/models/CalendarDay.java
> +    private int dayNr;
space needed

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/models/CalendarDay.java
> +    private int dayNr;
don't use Nr or other shortcuts ... it makes the code more easily to read if you are using full words

2019-10-15 10:36 UTC, grauralex92 commented on app/src/main/java/com/endava/myendava/models/Event.java
> +    private int participantsNr;
same as for dayNr

2019-10-16 08:27 UTC, grauralex92 approved these changes

2019-10-16 08:37 UTC, merged